import { Button } from '@core/ui'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => (
	<div>
		<Head>
			<title>Create Next App</title>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
		</Head>
		<Button />
	</div>
)

export default Home
