plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: '@yarnpkg/plugin-stage'
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: 'https://yarn.build/latest'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  '@spa5k/eslint-config@*':
    dependencies:
      'eslint': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      typescript: '*'
